const PERMISSIONS = {
  EMPLOYEE_LIST: 'employee.list',
  EMPLOYEE_VIEW: 'employee.view',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_DELETE: 'employee.delete',
  ATTENDANCE_LIST: 'attendance.list',
  ATTENDANCE_CHECK_IN: 'attendance.checkin',
  ATTENDANCE_CHECK_OUT: 'attendance.checkout',
  LEAVE_LIST: 'leave.list',
  LEAVE_CREATE: 'leave.create',
  LEAVE_APPROVE: 'leave.approve',
  LEAVE_REJECT: 'leave.reject',
};

const ROLE_DEFAULT_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  HR_ADMIN: [
    PERMISSIONS.EMPLOYEE_LIST,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.ATTENDANCE_LIST,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_CHECK_OUT,
    PERMISSIONS.LEAVE_LIST,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
  ],
  MANAGER: [
    PERMISSIONS.EMPLOYEE_LIST,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.ATTENDANCE_LIST,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_CHECK_OUT,
    PERMISSIONS.LEAVE_LIST,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
  ],
  EMPLOYEE: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.ATTENDANCE_LIST,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_CHECK_OUT,
    PERMISSIONS.LEAVE_LIST,
    PERMISSIONS.LEAVE_CREATE,
  ],
};

module.exports = {
  PERMISSIONS,
  ROLE_DEFAULT_PERMISSIONS,
};
